services:
  backend:
    build: ./backend
    ports:
      - "${DOCKER_PMD_PORT}:${DOCKER_PMD_PORT}"
    volumes:
    - workdata:/app/work

  frontend:
    build: ./frontend
    ports:
      - "${DOCKER_FRONTEND_PORT}:${DOCKER_FRONTEND_PORT}"
    depends_on:
      - backend

volumes:
  workdata:
